- name: Accounts_manage | Create groups
  ansible.builtin.group:
    name: '{{ item.name }}'
  with_items: "{{ accounts_manage_groups }}"
  when:
    - accounts_manage_groups is defined
    - item.host_groups is defined and (item.host_groups == "all" or item.host_groups in group_names)

- name: Accounts_manage | Configure sudoers
  ansible.builtin.copy:
    dest: /etc/sudoers.d/sudoers
    content: "{{ accounts_manage_sudoers }}"
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'
  when: accounts_manage_sudoers is defined

- name: Accounts_manage | Configure sudoers
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ item.name }}"
    content: "{{ item.rule }}"
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'
  with_items: "{{ accounts_manage_sudoers_rules }}"
  when: accounts_manage_sudoers_rules is defined

- name: Accounts_manage | Incluse tasks
  ansible.builtin.include_tasks: "user.yaml"
  loop: "{{ accounts_manage_users }}"
  when:
    - accounts_manage_users is defined
    - item.host_groups is defined and (item.host_groups == "all" or item.host_groups in group_names)
